spring.application.name=department-service

server.port=8082

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/departmentdb
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.datasource.driver-class-name=org.postgresql.Driver

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

department.message=Department Service Configuration Loaded Successfully
